[github]
token = "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"
GITHUB_TOKEN = "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"
GITHUB_REPO = "UdinTarmiji/finance-data"

github_token = "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"
repo_owner = "UdinTarmiji"         # ← ini adalah username GitHub kamu
repo_name = "finance-data"         # ← ini adalah nama repository tempat file disimpan
